### ISSUE TITLE
Redis / MySQL

### ISSUE THREAD

**Issue by firezdog** [frutik/quepid-kubernetes#2]
This seems to assume that the Redis and MySQL you want to use are already up and you just need to specify the proper credentials for access.  Is this correct?  And if so, why not show how they can be set up as part of the guide too?

**Comment by frutik** [comment]
yes, usually, I use redis and mysql as a service (both available in aws/gcp). so, manifests and instructions tailored to that use case

**Comment by frutik** [comment]
> why not show how they can be set up as part of the guide too?

Okay, I will try to write an article on medium in coming days

**Comment by firezdog** [comment]
It might be preferable to use the hosted solutions -- I'm not sure (otherwise you have to set up your own failover solutions) -- but it would at least be nice to also either discuss yourself or include resources on how to set that up.

**Comment by firezdog** [comment]
I was able to get everything working (in some sense of that word) using a configuration like this -- obv. not ideal from a security perspective, but I just wanted to figure out how this is supposed to be set up:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quepid
  namespace: quepid
  labels:
    app: quepid
spec:
  selector:
    matchLabels:
      app: quepid
  replicas: 1
  template:
    metadata:
      labels:
        app: quepid
    spec:
      containers:
        - name: quepid
          image: o19s/quepid:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "550m" 
              memory: "500Mi"
            limits:
              cpu: "650m"
              memory: "500Mi"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: common
            - configMapRef:
                name: credentials
        - name: quepid-redis
          image: redis:7.2.0-alpine
          ports:
            - containerPort: 6379
        - name: quepid-sql
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: db
      restartPolicy: Always
```
